// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uuhomdwyzznodzietggm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV1aG9tZHd5enpub2R6aWV0Z2dtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzNzI5MzksImV4cCI6MjA2Njk0ODkzOX0.tC64VFpXIlTek7cR1hTJV7gLEH79R9-nVcYa04hHLDQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});